config/routes.rb
Rails.application.routes.draw do
  resources :empresas
  resources :consultors
  resources :redes
  devise_for :users
  get 'welcome/index'
  root 'welcome#index'
  get 'consultors/:id/delete' => 'consultors#destroy', as: :delete_consultor
  get 'redes/:id/delete' => 'redes#destroy', as: :delete_rede
  get 'empresas/:id/delete' => 'empresas#destroy', as: :delete_empresa

end

app/models/rede.rb
class Rede < ActiveRecord::Base
	 validates :nome, presence: true, uniqueness: true
	has_many :consultors
	has_many :empresas, :through => :consultors
end

app/controllers/redes_controller.rb
class RedesController < ApplicationController
  before_action :set_rede, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /redes
  # GET /redes.json
  def index
    @redes = Rede.all
  end

  # GET /redes/1
  # GET /redes/1.json
  def show
  end

  # GET /redes/new
  def new
    @rede = Rede.new

    @todos_consultores = Consultor.all
    @rede_consultores = @rede.consultors.build
  end

  # GET /redes/1/edit
  def edit
  end

  # POST /redes
  # POST /redes.json
  def create
    @rede = Rede.new(rede_params)
       
    respond_to do |format|
      if @rede.save
        @nome = @rede.nome
        format.html { redirect_to @rede, notice: "A Rede: #{@nome} foi criada com sucesso." }
        format.json { render :show, status: :created, location: @rede }
      else
        format.html { render :new }
        format.json { render json: @rede.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /redes/1
  # PATCH/PUT /redes/1.json
  def update
    respond_to do |format|
      if @rede.update(rede_params)
        @nome = @rede.nome
        format.html { redirect_to @rede, notice: "A Rede: #{@nome} foi criada com sucesso." }
        format.json { render :show, status: :ok, location: @rede }
      else
        format.html { render :edit }
        format.json { render json: @rede.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /redes/1
  # DELETE /redes/1.json
  def destroy
    @nome = @rede.nome
    @rede.destroy
    respond_to do |format|
      format.html { redirect_to redes_url, notice: "A Rede: #{@nome} foi deletada." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rede
      @rede = Rede.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rede_params
      params.require(:rede).permit(:nome)
    end
end

app/helpers/redes_helper.rb
module RedesHelper
end

app/views/redes/_form.html.erb
<%= form_for @rede, :html => { :class => "form-horizontal rede" } do |f| %>

  <% if @rede.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@rede.errors.count, "error") %> prohibited this rede from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @rede.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :nome, :class => 'form-control' %>
    </div>
    <%=f.error_span(:nome) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                redes_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/redes/edit.html.erb
<%- model_class = Rede -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/redes/index.html.erb
<%- model_class = Rede -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @redes.each do |rede| %>
      <tr>
        <td><%= link_to rede.id, rede_path(rede) %></td>
        <td><%= rede.nome %></td>
        <td><%=l rede.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      rede_path(rede), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_rede_path(rede), :class => 'btn btn-default btn-xs' %>
          <%= link_to 'Deletar', delete_rede_path(rede) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_rede_path,
            :class => 'btn btn-primary' %>

app/views/redes/new.html.erb
<%- model_class = Rede -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/redes/show.html.erb
<%- model_class = Rede -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @rede.nome %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              redes_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_rede_path(@rede), :class => 'btn btn-default' %>
<%= link_to 'Deletar', delete_rede_path(@rede) %>