config/routes.rb
Rails.application.routes.draw do
  resources :empresas
  resources :consultors
  resources :redes
  devise_for :users
  get 'welcome/index'
  root 'welcome#index'
  get 'consultors/:id/delete' => 'consultors#destroy', as: :delete_consultor
  get 'redes/:id/delete' => 'redes#destroy', as: :delete_rede
  get 'empresas/:id/delete' => 'empresas#destroy', as: :delete_empresa

end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
	 validates :nome, presence: true
	 validates :cnpj, presence: true, uniqueness: true
	has_many :parts, dependent: :destroy
	has_many :consultors, :through => :parts
end

app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController
  before_action :set_empresa, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /empresas
  # GET /empresas.json
  def index
    @empresas = Empresa.all
  end

  # GET /empresas/1
  # GET /empresas/1.json
  def show
    @consultores = @empresa.consultors
  end

  # GET /empresas/new
  def new
    @empresa = Empresa.new
    @todos_consultores = Consultor.all
    @empresa_consultores = @empresa.consultors.build
  end

  # GET /empresas/1/edit
  def edit
  end

  # POST /empresas
  # POST /empresas.json
  def create
    @empresa = Empresa.new(empresa_params)
    @cons = Array.new
    if params != nil
      @x = params[:consultors]
      if @x != nil
        @x[:id].each do |consultor|
        
          @cons << Consultor.find(consultor) if !consultor.empty?
        
        end
      end
    end    
    
    @empresa.consultors = @cons if @cons != nil

    respond_to do |format|
      if @empresa.save
        @nome = @empresa.nome
        format.html { redirect_to @empresa, notice: "A Empresa: #{@nome} foi criada com sucesso." }
        format.json { render :show, status: :created, location: @empresa }
      else
        format.html { render :new }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /empresas/1
  # PATCH/PUT /empresas/1.json
  def update
    respond_to do |format|
      if @empresa.update(empresa_params)
        @nome = @empresa.nome
        format.html { redirect_to @empresa, notice: "A Empresa: #{@nome} foi editada com sucesso." }
        format.json { render :show, status: :ok, location: @empresa }
      else
        format.html { render :edit }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empresas/1
  # DELETE /empresas/1.json
  def destroy
    @nome = @empresa.nome
    @empresa.destroy    
    respond_to do |format|
      format.html { redirect_to empresas_url, notice: "A Empresa: #{@nome} foi deletada."  }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empresa
      @empresa = Empresa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def empresa_params
      params.require(:empresa).permit(:nome, :cnpj, :venda, :gasto)
    end
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/views/empresas/_form.html.erb
<%= form_for @empresa, :html => { :class => "form-horizontal empresa" } do |f| %>

  <% if @empresa.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@empresa.errors.count, "error") %> prohibited this empresa from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @empresa.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :nome, :class => 'form-control' %>
    </div>
    <%=f.error_span(:nome) %>
  </div>
  <div class="form-group">
    <%= f.label :cnpj, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :cnpj, :class => 'form-control' %>
    </div>
    <%=f.error_span(:cnpj) %>
  </div>
  <div class="form-group">
    <%= f.label :venda, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :venda, :class => 'form-control' %>
    </div>
    <%=f.error_span(:venda) %>
  </div>
  <div class="form-group">
    <%= f.label :gasto, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :gasto, :class => 'form-control' %>
    </div>
    <%=f.error_span(:gasto) %>
  </div>
  <% if @empresa_consultores != nil %>
    <%= f.fields_for(@empresa_consultores) do |ce| %>
      <div class="form-group">
        <%= ce.label "Consultores", :class => 'control-label col-lg-2' %>
          <div class="col-lg-10">
            <%= collection_select(:consultors, :id, @todos_consultores, :id, :nome, {}, {multiple: true})%>
          </div>
      </div>
    <% end %>
  <% end %> 
  
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                empresas_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/empresas/edit.html.erb
<%- model_class = Empresa -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form_edit' %>

app/views/empresas/index.html.erb
<%- model_class = Empresa -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:cnpj) %></th>
      <th><%= model_class.human_attribute_name(:venda) %></th>
      <th><%= model_class.human_attribute_name(:gasto) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @empresas.each do |empresa| %>
      <tr>
        <td><%= link_to empresa.id, empresa_path(empresa) %></td>
        <td><%= empresa.nome %></td>
        <td><%= empresa.cnpj %></td>
        <td><%= empresa.venda %></td>
        <td><%= empresa.gasto %></td>
        <td><%=l empresa.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      empresa_path(empresa), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_empresa_path(empresa), :class => 'btn btn-default btn-xs' %>
          <td><%= link_to 'Deletar', delete_empresa_path(empresa) %></td>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_empresa_path,
            :class => 'btn btn-primary' %>

app/views/empresas/new.html.erb
<%- model_class = Empresa -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/empresas/show.html.erb
<%- model_class = Empresa -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @empresa.nome %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cnpj) %>:</strong></dt>
  <dd><%= @empresa.cnpj %></dd>
  <dt><strong><%= model_class.human_attribute_name(:venda) %>:</strong></dt>
  <dd><%= @empresa.venda %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gasto) %>:</strong></dt>
  <dd><%= @empresa.gasto %></dd>
</dl>

<table class="table table-striped">
    <thead>
      <tr>
        <th>Consultores: </th>
        <th colspan="3"></th>
      </tr>
    </thead>
    
    <tbody>
      <% if @consultores != nil %> 
        <% if @consultores.size > 0 %>
          <% @consultores.each do |consultor| %>
            <tr>
              <td><%= link_to consultor.nome, consultor %></td>
            </tr>
          <% end %>  
        <% else %>  
          <tr>
            <td>Não possui vinculo com consultores.</td>
          </tr>
        <% end %>
    <% end %>    
    </tbody>
  </table>

<%= link_to t('.back', :default => t("helpers.links.back")),
              empresas_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_empresa_path(@empresa), :class => 'btn btn-default' %>
<td><%= link_to 'Deletar', delete_empresa_path(@empresa) %></td>